{% set name = "jsonnet-language-server" %}
{% set version = "0.15.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/grafana/jsonnet-language-server/archive/v{{ version }}.tar.gz
  sha256: 085085ad1c8c75cb178876726b5a974027058cab9a83dff6435aa5681f687517

build:
  number: 0

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  commands:
    - jsonnet-language-server --help

about:
  home: https://github.com/grafana/jsonnet-language-server
  license: AGPL-3.0-or-later
  license_file:
    - LICENSE
    - license-files/
  summary: A Language Server Protocol (LSP) server for Jsonnet
  dev_url: https://github.com/grafana/jsonnet-language-server

extra:
  recipe-maintainers:
    - danielnachun
