schema_version: 1

context:
  version: "0.17.0"

package:
  name: jsonnet-language-server
  version: ${{ version }}

source:
  url: https://github.com/grafana/jsonnet-language-server/archive/v${{ version }}.tar.gz
  sha256: 7d51fbd633475f449772c95e410ffb498df5e4e2102c7ac49072a76f38a5b98b

build:
  number: 0

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script:
      - jsonnet-language-server --help

about:
  license: AGPL-3.0-or-later
  license_file:
    - LICENSE
    - license-files/
  summary: A Language Server Protocol (LSP) server for Jsonnet
  homepage: https://github.com/grafana/jsonnet-language-server
  repository: https://github.com/grafana/jsonnet-language-server

extra:
  recipe-maintainers:
    - danielnachun
